export enum ErrorCode {
  // Auth errors
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  TOKEN_INVALID = "TOKEN_INVALID",
  
  // Hospital errors
  HOSPITAL_NOT_FOUND = "HOSPITAL_NOT_FOUND",
  
  // Child errors
  CHILD_NOT_FOUND = "CHILD_NOT_FOUND",
  
  // Validation errors
  VALIDATION_FAILED = "VALIDATION_FAILED",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD",
  
  // File errors
  UPLOAD_FAILED = "UPLOAD_FAILED",
  FILE_NOT_FOUND = "FILE_NOT_FOUND",
  FILE_TOO_LARGE = "FILE_TOO_LARGE",
  INVALID_INPUT = "INVALID_INPUT",
  INVALID_FILE_TYPE = "INVALID_FILE_TYPE",
  STORAGE_ERROR = "STORAGE_ERROR",
  
  // Permission errors
  INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS",
  
  // Business rule errors
  BUSINESS_RULE_VIOLATION = "BUSINESS_RULE_VIOLATION",
  
  // Resource errors
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  CONSTRAINT_VIOLATION = "CONSTRAINT_VIOLATION",
  
  // Database errors
  DATABASE_ERROR = "DATABASE_ERROR",
  DUPLICATE_ENTRY = "DUPLICATE_ENTRY",
  TRANSACTION_FAILED = "TRANSACTION_FAILED",
  
  // System errors
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  MAINTENANCE_MODE = "MAINTENANCE_MODE",
  
  // Remove these (not needed):
  // ENROLLMENT_FULL, ENROLLMENT_CLOSED, EMAIL_ALREADY_EXISTS, PHONE_ALREADY_EXISTS, etc.
}